"""G13 Button Layout - Generated by g13_calibrate.py"""

KEYBOARD_WIDTH = 1024
KEYBOARD_HEIGHT = 1024


def _box(x, y, w, h):
    """Create position dict."""
    return {"x": int(x), "y": int(y), "width": int(w), "height": int(h)}


G13_BUTTON_POSITIONS = {
    # M-keys row
    "M1": _box(434, 374, 28, 18),
    "M2": _box(483, 374, 28, 18),
    "M3": _box(531, 374, 28, 18),
    "MR": _box(583, 374, 28, 18),
    # Row 1: G1-G7 (smooth slope ~1px/key matching device angle)
    "G1": _box(385, 408, 38, 28),
    "G2": _box(427, 409, 38, 28),
    "G3": _box(469, 410, 38, 28),
    "G4": _box(512, 411, 38, 28),
    "G5": _box(556, 412, 38, 28),
    "G6": _box(599, 413, 38, 28),
    "G7": _box(646, 414, 38, 28),
    # Row 2: G8-G14 (smooth slope, even 42px x-spacing)
    "G8": _box(378, 446, 38, 28),
    "G9": _box(420, 447, 38, 28),
    "G10": _box(462, 448, 38, 28),
    "G11": _box(504, 449, 38, 28),
    "G12": _box(546, 450, 38, 28),
    "G13": _box(588, 451, 38, 28),
    "G14": _box(630, 452, 38, 28),
    # Row 3: G15-G19 (smooth slope, even 47px x-spacing)
    "G15": _box(413, 484, 38, 28),
    "G16": _box(460, 485, 38, 28),
    "G17": _box(507, 486, 38, 28),
    "G18": _box(554, 487, 38, 28),
    "G19": _box(601, 488, 38, 28),
    # Row 4: G20-G22 (smooth slope, even 42px x-spacing)
    "G20": _box(464, 525, 42, 28),
    "G21": _box(506, 526, 42, 28),
    "G22": _box(548, 527, 42, 28),
    # Thumb buttons
    "LEFT": _box(603, 579, 28, 22),
    "DOWN": _box(644, 623, 28, 22),
    "STICK": _box(644, 570, 35, 35),
}

JOYSTICK_AREA = {"x": 644, "y": 570, "width": 35, "height": 35}
LCD_AREA = {"x": 385, "y": 158, "width": 160, "height": 45}
